baseURL: https://jadin.me/

menu:
    main:
        # - name: About Me
        #   url: /about
        #   pre: <span class="main-pages">
        #   post: </span>
        #   weight: 1
        - name: Bookmarks
          url: /bookmarks
          pre: <span class="main-pages">
          post: </span>
          weight: 2
        - name: Posts by date
          url: /all
          weight: 3
        - name: Posts by tag
          url: /tags
          weight: 4
        - name: Search
          url: /search
          weight: 5

title: Taylor Jadin
theme:
  - PaperMod
languageCode: en-us
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
    home:
        - HTML
        - RSS
        - JSON
Permalinks:
  post: '/:slug'
params:
  defaultTheme: dark
  disableThemeToggle: true
  env: production
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  cover:
    responsiveImages: false
  homeInfoParams:
      Content1: I am an Instructional Technologist at St. Norbert College. This site is where I try to collect the work I do in the open, including podcasting and the ocassional blog post.
      Content2: I [tweet](https://twitter.com/taylorjadin), [post pictures to Instagram](https://www.instagram.com/taylor_jadin/), and [occasionally write code](https://github.com/taylorjadin). My wife and I also sometimes [stream](http://twitch.tv/jadinapproved) or [record a podcast](https://anchor.fm/taylor-jadin) under the name Jadin Approved.